/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.text.DecimalFormat;

/**
 *
 * @author s.lucas
 */
public class fGestorEscolar extends javax.swing.JFrame {

    /**
     * Creates new form fGestorEscolar
     */
    public fGestorEscolar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBackPanel = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbAluno = new javax.swing.JLabel();
        txtNomeAluno = new javax.swing.JTextField();
        lbNota1 = new javax.swing.JLabel();
        txtNota1 = new javax.swing.JTextField();
        txtNota2 = new javax.swing.JTextField();
        lbNota2 = new javax.swing.JLabel();
        txtNota3 = new javax.swing.JTextField();
        lbNota3 = new javax.swing.JLabel();
        btnGerarBoletim = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbTituloBoletim = new javax.swing.JLabel();
        lbAlunoBol = new javax.swing.JLabel();
        lbNota1Bol = new javax.swing.JLabel();
        lbNota2Bol = new javax.swing.JLabel();
        lbNota3Bol = new javax.swing.JLabel();
        lbMediaBol = new javax.swing.JLabel();
        lbResultadoBol = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbTextPane = new javax.swing.JTextPane();
        txtNomeBol = new javax.swing.JLabel();
        txtNota1Bol = new javax.swing.JLabel();
        txtNota2Bol = new javax.swing.JLabel();
        txtNota3Bol = new javax.swing.JLabel();
        txtMediaBol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBackPanel.setBackground(new java.awt.Color(204, 255, 255));

        lbTitulo.setFont(new java.awt.Font("Bodoni MT", 1, 20)); // NOI18N
        lbTitulo.setText("GESTOR ESCOLAR");
        lbTitulo.setAlignmentY(0.0F);

        lbAluno.setFont(new java.awt.Font("Bodoni MT", 1, 15)); // NOI18N
        lbAluno.setText("Aluno(a):");

        txtNomeAluno.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        txtNomeAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAlunoActionPerformed(evt);
            }
        });

        lbNota1.setFont(new java.awt.Font("Bodoni MT", 1, 15)); // NOI18N
        lbNota1.setText("Nota 1");

        txtNota1.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        txtNota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota1ActionPerformed(evt);
            }
        });

        txtNota2.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        txtNota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota2ActionPerformed(evt);
            }
        });

        lbNota2.setFont(new java.awt.Font("Bodoni MT", 1, 15)); // NOI18N
        lbNota2.setText("Nota 2");

        txtNota3.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        txtNota3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota3ActionPerformed(evt);
            }
        });

        lbNota3.setFont(new java.awt.Font("Bodoni MT", 1, 15)); // NOI18N
        lbNota3.setText("Nota 3");

        btnGerarBoletim.setBackground(new java.awt.Color(80, 199, 120));
        btnGerarBoletim.setFont(new java.awt.Font("Bodoni MT", 1, 15)); // NOI18N
        btnGerarBoletim.setText("Gerar Boletim");
        btnGerarBoletim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarBoletimActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(243, 112, 83));
        btnLimpar.setFont(new java.awt.Font("Bodoni MT", 1, 15)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbTituloBoletim.setFont(new java.awt.Font("Bodoni MT", 1, 20)); // NOI18N
        lbTituloBoletim.setText("BOLETIM");

        lbAlunoBol.setFont(new java.awt.Font("Bodoni MT", 1, 15)); // NOI18N
        lbAlunoBol.setText("Aluno(a):");

        lbNota1Bol.setFont(new java.awt.Font("Bodoni MT", 1, 15)); // NOI18N
        lbNota1Bol.setText("Nota 1:");

        lbNota2Bol.setFont(new java.awt.Font("Bodoni MT", 1, 15)); // NOI18N
        lbNota2Bol.setText("Nota 2:");

        lbNota3Bol.setFont(new java.awt.Font("Bodoni MT", 1, 15)); // NOI18N
        lbNota3Bol.setText("Nota 3:");

        lbMediaBol.setFont(new java.awt.Font("Bodoni MT", 1, 15)); // NOI18N
        lbMediaBol.setText("Média:");

        lbResultadoBol.setFont(new java.awt.Font("Bodoni MT", 0, 15)); // NOI18N
        lbResultadoBol.setText("RESULTADO:");

        lbTextPane.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        lbTextPane.setAutoscrolls(false);
        jScrollPane1.setViewportView(lbTextPane);

        txtNomeBol.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        txtNomeBol.setText("----");

        txtNota1Bol.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        txtNota1Bol.setText("----");

        txtNota2Bol.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        txtNota2Bol.setText("----");

        txtNota3Bol.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        txtNota3Bol.setText("----");

        txtMediaBol.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        txtMediaBol.setText("----");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbAlunoBol)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomeBol))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbNota1Bol)
                        .addGap(18, 18, 18)
                        .addComponent(txtNota1Bol))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbNota2Bol)
                        .addGap(18, 18, 18)
                        .addComponent(txtNota2Bol))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbNota3Bol)
                        .addGap(18, 18, 18)
                        .addComponent(txtNota3Bol))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbMediaBol)
                        .addGap(18, 18, 18)
                        .addComponent(txtMediaBol)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbResultadoBol)
                    .addComponent(lbTituloBoletim)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAlunoBol)
                            .addComponent(txtNomeBol))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNota1Bol)
                            .addComponent(txtNota1Bol))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNota2Bol)
                            .addComponent(txtNota2Bol))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNota3Bol)
                            .addComponent(txtNota3Bol))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMediaBol)
                            .addComponent(txtMediaBol))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbTituloBoletim)
                        .addGap(23, 23, 23)
                        .addComponent(lbResultadoBol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jBackPanelLayout = new javax.swing.GroupLayout(jBackPanel);
        jBackPanel.setLayout(jBackPanelLayout);
        jBackPanelLayout.setHorizontalGroup(
            jBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBackPanelLayout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(316, 316, 316))
            .addGroup(jBackPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbAluno)
                    .addGroup(jBackPanelLayout.createSequentialGroup()
                        .addGroup(jBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNota1)
                            .addComponent(txtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNota2)
                            .addComponent(txtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNota3)
                            .addComponent(txtNota3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jBackPanelLayout.createSequentialGroup()
                            .addComponent(btnGerarBoletim)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnLimpar))
                        .addComponent(txtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        jBackPanelLayout.setVerticalGroup(
            jBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBackPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jBackPanelLayout.createSequentialGroup()
                        .addComponent(lbNota2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jBackPanelLayout.createSequentialGroup()
                        .addComponent(lbTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbAluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbNota1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jBackPanelLayout.createSequentialGroup()
                        .addComponent(lbNota3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGerarBoletim)
                    .addComponent(btnLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBackPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAlunoActionPerformed
                
    }//GEN-LAST:event_txtNomeAlunoActionPerformed

    private void txtNota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNota1ActionPerformed

    private void txtNota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNota2ActionPerformed

    private void txtNota3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNota3ActionPerformed

    private void btnGerarBoletimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarBoletimActionPerformed
        String nome, result;
        double n1, n2, n3, media;
        
        DecimalFormat i = new DecimalFormat("0");
        DecimalFormat f = new DecimalFormat("0.0");
                
        nome = txtNomeAluno.getText();
        n1 = Double.parseDouble(txtNota1.getText());
        n2 = Double.parseDouble(txtNota2.getText());
        n3 = Double.parseDouble(txtNota3.getText());
        media = (n1 + n2 + n3) / 3;
        txtNomeBol.setText(nome);
        txtNota1Bol.setText(String.valueOf(f.format(n1)));
        txtNota2Bol.setText(String.valueOf(f.format(n2)));
        txtNota3Bol.setText(String.valueOf(f.format(n3)));
        txtMediaBol.setText(String.valueOf(f.format(media)));
        if(media >= 7){
            result = "APROVADO";
        } else {
            result = "REPROVADO";
        }
        lbTextPane.setText("O(A) Aluno(a) " + nome + " está " + result + ", com média " + f.format(media) + ".");
    }//GEN-LAST:event_btnGerarBoletimActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtNomeAluno.setText("");
        txtNota1.setText("");
        txtNota2.setText("");
        txtNota3.setText("");
        txtNomeBol.setText("");
        txtNota1Bol.setText("");
        txtNota2Bol.setText("");
        txtNota3Bol.setText("");
        txtMediaBol.setText("");
        lbTextPane.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fGestorEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fGestorEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fGestorEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fGestorEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fGestorEscolar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarBoletim;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JPanel jBackPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAluno;
    private javax.swing.JLabel lbAlunoBol;
    private javax.swing.JLabel lbMediaBol;
    private javax.swing.JLabel lbNota1;
    private javax.swing.JLabel lbNota1Bol;
    private javax.swing.JLabel lbNota2;
    private javax.swing.JLabel lbNota2Bol;
    private javax.swing.JLabel lbNota3;
    private javax.swing.JLabel lbNota3Bol;
    private javax.swing.JLabel lbResultadoBol;
    private javax.swing.JTextPane lbTextPane;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbTituloBoletim;
    private javax.swing.JLabel txtMediaBol;
    private javax.swing.JTextField txtNomeAluno;
    private javax.swing.JLabel txtNomeBol;
    private javax.swing.JTextField txtNota1;
    private javax.swing.JLabel txtNota1Bol;
    private javax.swing.JTextField txtNota2;
    private javax.swing.JLabel txtNota2Bol;
    private javax.swing.JTextField txtNota3;
    private javax.swing.JLabel txtNota3Bol;
    // End of variables declaration//GEN-END:variables
}
